### PR TITLE
Update Eclipse links to 2018-12 release

### LINKED ISSUE #239: Upgrade Eclipse to 4.10/2018-12 release
A new Eclipse platform should be released 12/19, let's get this up to date for spring, as we're currently on 4.8.

https://wiki.eclipse.org/Simultaneous_Release

### PR DESCRIPTION
**Pull request by cfrome77**
closes #239

### CODE REVIEW

**Comment by cfrome77** [comment]
accidentally created branch inside of here instead of my fork, and there was no way for me to delete it since it says the branch is protected.

**Comment by ripleymj** [comment]
I'm sure we can clean up the branch somehow, after we merge this. Can you update the sha1 hash as well? I'm getting `e5706798b7c9f1d34c9b82460a1d99a3cd1d286b` here, but please confirm on your side.

**Comment by kylelaker** [comment]
@cfrome77 when updating the sha1sum, you won't be able to push to the branch on this repo because of the branch protection. You'll have to push the branch to your own repo and open a new PR as GitHub doesn't allow changing the source branch of a PR.

It should work just like normal with a:

```
git push <remote> <branch>
```

And you should then be able to open a new PR.

Sorry for the inconvenience, but you can go ahead and close this one when you open the new one and I'll take care of deleting the branch on this repo.

**Comment by cfrome77** [comment]
closed in favor of #242

**Pull request closed without merging**
