### PR TITLE
Update Eclipse to 2020-12

### LINKED ISSUE #425: New Eclipse version is available
A new version of Eclipse IDE for Java Developers is available.

Version: 2020-12
URL: http://mirror.math.princeton.edu/pub/eclipse/technology/epp/downloads/release/2020-12/R/eclipse-java-2020-12-R-linux-gtk-x86_64.tar.gz
SHA1: 3a77893d865e25fb9e28f4b26efd59279ff79457

Does this need to go into `ulyana` or `main` sufficient?

### PR DESCRIPTION
**Pull request by ripleymj**
Closes #425

### CODE REVIEW

**Comment by ripleymj** [comment]
Tests should pass once rebased against #427

**Comment by kylelaker** [comment]
Rebase shouldn't be necessary to resolve the issue with Packer lint; since the changes aren't to the same file, git `checkout` action should cleanly merge them to what `main` would be if this were merged. Re-running the jobs should be all that's required. Seems like the new Eclipse file hasn't been synced to all mirrors yet though.

**Comment by ripleymj** [comment]
Yep, getting that lagging mirror feeling now.

**Review by kylelaker — APPROVED** [review]
Looks like the sync is done (well enough)

**Pull request merged**
