### PR TITLE
Rewrite wrapper script

### LINKED ISSUE #89: Install Zenity as a dependency
This should be installed in Mint by default; however, since it will be critical to the errors and warnings in the Ansible wrapper script, we should try our best to ensure it is installed. It should definitely be added to the OEM role; however, I am uncertain on the value of adding it to common.

### LINKED ISSUE #92: Enable logging
Before we ship to users we should consider some method of storing logs of runs. None of them are perfect. A few options include:
 * using `tee` in the wrapper script
* setting `log_path` in `ansible.cfg` [[1]]
* setting an `ANSIBLE_LOG_PATH` environment variable in the wrapper

|  |  Pros | Cons |
|-| -----|------|
|`tee`| We can create files, directory ahead of time; we can use shell variables in the file path easily, can log based on tags passed  | It's another command to have to work with and worry  about mucking with exit codes; only works when the wrapper is used  |
|`log_path`| Works regardless of whether or not wrapper is used | More difficult to configure name dynamically (date, time, etc) |
|`ANSIBLE_LOG_PATH`| Benefits of `tee` plus we can allow users to set the environment variable themselves and not override if they've set it  | Only works when the wrapper is used |

We could use a combination of `log_path` and `ANSIBLE_LOG_PATH`. Since Ansible checks the environment first (see [2] after the list of links), we could set a log file in the wrapper `/opt/vm/logs/$TAG/$(date '+%Y%m%d-%H%M%S').log`. In the event that doesn't work, we can have `log_path` set to `/opt/vm/logs/last_run.log`, or a more-likely-to-exist directory `/var/logs/vm_ansible.log`. I really don't want to use `tee` unless there is a compelling reason to do so.

I would like to ship this in the spring VM so that we can get logs from users if (*when*) things go wrong; however, I will let someone else target this to a milestone. It doesn't seem like it'd be awful to implement, but deciding the right way to do it is the trickier part. A nice thing is that all of them are easily changeable since they'd all be set in files we control.

[1]: http://ansible-manual.readthedocs.io/en/latest/intro_configuration.html#log-path
[2]: http://ansible-manual.readthedocs.io/en/latest/intro_configuration.html

### LINKED ISSUE #93: Convert install script to Python
Let's move discussion about this to its own issue, instead of burying it in a PR or comments on a gist: https://gist.github.com/kylelaker/8e8bc9f97514bcda6bfa813d7e7a6f72

### PR DESCRIPTION
**Pull request by kylelaker**
Rewrite the Ansible wrapper script in Python to allow the user to select
which courses they need to have their machine configured for. Enable
logging by specifying a path in ansible.cfg. Remove previous wrappers
and installed desktop shortcuts in favor of the new wrapper

Resolves #93 
Resolves #92 

Closes #62

### CODE REVIEW

**Comment by kylelaker** [comment]
@ripleymj Forced pushed a chance to fix that

**Comment by ripleymj** [comment]
I think this works well enough to merge, but I'm going to hold off until later today when I can take one more look at the whole thing.

**Comment by kylelaker** [comment]
@ripleymj  I pushed a change to rebase this on top of master to avoid merge conflicts

**Comment by kylelaker** [comment]
Forgot to comment but the latest version has refactored the dialog creation out to a separate method. It doesn't clean stuff up too much, but hopefully it makes the dialogs slightly more uniform

**Comment by ripleymj** [comment]
I've approved the changes. When you're ready, please merge, create a branch, and tag beta1.

**Comment by kylelaker** [comment]
This can be merged once we have something for #84 and #65.

**Comment by ripleymj** [comment]
Need to rethink the effect on #90 here

**Comment by kylelaker** [comment]
Good point. Due to #97, #89 and #90 are no longer closed by this. I will remove them from the initial message to prevent those from being closed upon merge.

**Comment by kylelaker** [comment]
I agree on the Cancel vs Quit

**Comment by kylelaker** [comment]
Two more commits. One to fix an issue that may come up soon and another to make things cleaner should strings need to be updated in the future.

**Comment by kylelaker** [comment]
Hopefully those are two of the last commits that need to be pushed (and one of the last reviews you'll need to do). When we get ready to merge, I'll rebase this whole thing on master and squash it all into one big commit. Any other changes before then I'll keep pushing as individual commits because I think they more clearly highlight what changes each time I push and make you have to re-review.

**Comment by kylelaker** [comment]
Once all other remaining PRs are merged and we get a resolution to #84 I think we can go ahead and merge this monster as well

**Comment by kylelaker** [comment]
This has been rebased on top of master and all the commits have been squashed.

**Pull request merged**
