### PR TITLE
Install Zenity as a dependency

### LINKED ISSUE #89: Install Zenity as a dependency
This should be installed in Mint by default; however, since it will be critical to the errors and warnings in the Ansible wrapper script, we should try our best to ensure it is installed. It should definitely be added to the OEM role; however, I am uncertain on the value of adding it to common.

### PR DESCRIPTION
**Pull request by kylelaker**
Resolves #89

### CODE REVIEW

**Comment by ripleymj** [comment]
Pushed a small tweak for your consideration

**Comment by ripleymj** [comment]
Also, I swear I didn't do this so that we'd need an unbiased review from a 3rd party.

**Comment by kylelaker** [comment]
Rebased this atop master to resolve merge conflicts

**Comment by kylelaker** [comment]
@ripleymj are we still waiting for a review from @Advill before merge?

**Pull request merged**
