### PR TITLE
Use data from /etc/os-release to determine what branch to pull

### PR DESCRIPTION
**Pull request by kylelaker**
The VERSION_CODENAME is how we will be tagging branches in the future.
Source /etc/os-release to get the VERSION_CODENAME variable and pass
that to ansible-pull's --checkout option. Report an error if
/etc/os-release does not exist.

This must not be merged until we create a branch for the Sylvia release.

### CODE REVIEW

**Comment by ripleymj** [comment]
Thinking out loud, but could we add a cheat code to this to switch to master branch? Something like `if (hostname == "uugmaster")` to make ongoing development slightly easier.

**Comment by kylelaker** [comment]
We could do that. Or  have a file like`$HOME/.config/vm_config` and just source it to see if there's either `FORCE_BRANCH=<branch>` or `USE_MASTER=1`.

**Comment by ripleymj** [comment]
I like `FORCE_BRANCH` best of the three.

**Comment by kylelaker** [comment]
Closed by accidently deletinga  branch. Reopening

**Comment by kylelaker** [comment]
@ripleymj The discussed issues hopefully are mostly resolved with this latest commit.

**Comment by kylelaker** [comment]
Those specific concerns should be resolved in the latest force push

**Comment by kylelaker** [comment]
I will be pushing a series of commits to test with. I'll advise once this is ready for review again. Pushing to this branch makes testing easier, but unfortunately also updates the pull request

**Comment by kylelaker** [comment]
453b1a1 should be ready to be tested and reviewed

**Comment by kylelaker** [comment]
Rebased on top of master to resolve merge conflicts

**Comment by kylelaker** [comment]
@ripleymj don't hate me, but I did a thing: https://gist.github.com/kylelaker/8e8bc9f97514bcda6bfa813d7e7a6f72

Let me know what you think. In a lot of ways, it's better than this wrapper.

**Comment by kylelaker** [comment]
#94 is way better.

**Pull request closed without merging**
