### PR TITLE
Update jGRASP to 2.0.6

### LINKED ISSUE #348: Update to jGrasp 2.0.6
New release expected soon. Opening bug to track progress to spring image.

### PR DESCRIPTION
**Pull request by ripleymj**
Closes #348 

Need to run this at least once myself before merging.

### CODE REVIEW

**Comment by kylelaker** [comment]
#339 comes back with this PR.

**Comment by kylelaker** [comment]
I guess I should be specific about the issue with #339. There is a "Don't Show Again" button but there is another, earlier warning, for which that is not an option. That warning will always appear every time that jGRASP is launched. It would make for an unfortunate user experience for CS1 students to see that message every time they launch the IDE for their class.

Should we consider using the version of jGRASP with an integrated JDK?

**Comment by kylelaker** [comment]
Just want to note that the unsupported JDK warning persists even with this new re-released 2.0.6.

**Comment by ripleymj** [comment]
I really do not want to balloon out a 7MB download to a 270MB download, just for an identical JVM. jGRASP had promised they would include the Ubuntu build but seem to have dropped that, hopefully accidentally. The labs exhibit the same behavior, so I'm not concerned about students being suddenly presented with this error.

**Pull request merged**
