### PR TITLE
Add CS-361 to 261 option on install

### PR DESCRIPTION
**Pull request by Advill**
Closes jmunixusers/cs-vm-build#206

### CODE REVIEW

**Comment by ripleymj** [comment]
Whatever direction we decide to go, I think we need to put merging 361 on hold pending the outcome of @coledn's rewrite.

**Comment by kylelaker** [comment]
Welp... I feel like a jerk. I added a comment on #206 perhaps a little late explaining that we probably should split the tags for these courses. Would you mind looking at that comment and either giving your thoughts here?

Basically, my concerns are centered around 'What if we need to split 261 and 361 in the future' and I hadn't considered that previously when suggesting just modifying the script.

**Comment by Advill** [comment]
No worries. I can get that done fairly quickly tomorrow if we are more or less set on that option. None of my changes should interfere with @coledn 's changes, as I'm just messing with tags, supposedly localized entirely within the `local.yml` file and perhaps the readme. If it is preferred that I wait until uug to figure that out that is fine with me.

**Comment by kylelaker** [comment]
I'm okay if you start work on it; I just feel like there might be some questions left to answer such as:

 - 361 requires (at least) all of 261 minus y86, right?
 - It will also eventually require its own role since it needs it's own packages?
    - If so, what do we want to call that new role? We've already taken `adv-prog-pkgs` for 261.
    - If so, it should be created with `ansible-galaxy init <role_name>` in the `roles/` dir
 - Do we know what packages 361 needs?

**Comment by Advill** [comment]
To answer your questions in order as far as I know at the moment:
- Yes, even some of the packages in `adv-prog-pkgs` might be extraneous, but removing them likely isn't worth it.
- I'm not sure, for where we are right now in Aboutabl's class, it doesn't appear that we've needed anything else. I intend on ensuring that this is true, but haven't had the time to do so yet.
    - I think something to do with `multithreaded-prog-pkgs` could do
    - Yes, I've got this downloaded now, ansible was being weird about installing through pacman at first.
- As the year goes on, I'd be happy to add any packages that come up, but knowing Aboutabl I wouldn't expect anything too far outside the basic c libraries.

I'm certainly open to changes if we find different answers, my plan will be to implement things like this right now as it won't be that difficult of a change if we find things are different.

**Comment by kylelaker** [comment]
That all sounds good! I think I'm fine with having a basic 361 tag set up and then modifying as needed. Let's not create the new role until it's needed, though

**Comment by Advill** [comment]
closed in favor of #209

**Pull request closed without merging**
