### PR TITLE
Spring 2022 Updates for wrapper script

### PR DESCRIPTION
**Pull request by kylelaker**
This performs some fairly significant refactoring to the wrapper script. It's incomplete but I am opening it as a draft early to collect additional ideas or objections.

- [X] Experimental course support
- [X] Add Settings for all config values
- [X] Properly follow XDG Base Directory standard
- [X] Use YAML instead of JSON
- [x] ~Improve error message logic~
- [x] ~Improve UX of VTE~
- [x] Link to VM readme in Help menu
- [x] Investigate `sudo` + `AskPass` helper instead of `pkexec`
  - Would make it easier to target which steps run with `become`

### CODE REVIEW

**Comment by kylelaker** [comment]
`sudo` + `AskPass` doesn't really seem to be viable here

**Comment by kylelaker** [comment]
Also probably want to kick error logic and VTE stuff to another semester.

**Comment by kylelaker** [comment]
Going to move this back to draft until we see what's up with GTK 3/4 on Ubuntu 22.04/Mint 21.

**Comment by kylelaker** [comment]
Alright this should be good to go. Seems to work with the default packages in Mint and Ubuntu (unless I've done something to invalidate that assumption).

Big features are:
 - Support for experimental courses (added when we talked about needing testers for Robotics)
 - Using XDG directories correctly for configuration and now that pyYAML is available my default we can use YAML for the config
 - Makes everything we had a config value for available in settings (like allowing using the `main` branch)

**Review by ripleymj — APPROVED** [review]

**Pull request merged**
