### PR TITLE
Alert in cs354 if USB2.0/3.0 controller not present

### PR DESCRIPTION
**Pull request by kylelaker**
Completes one more step in #65

### CODE REVIEW

**Comment by kylelaker** [comment]
This should be tested for the following:

* [ ] More than one user
* [ ] Does it open the URL as root
* [ ] Does the text actually display properly

**Comment by kylelaker** [comment]
With more than one user, you get an error message, but adding "ignore_errors: yes" to the handler prevents that from marking the whole run as failed. It doesn't seem like it causes multiple dialogs to come up

**Comment by kylelaker** [comment]
Depends on #90

**Comment by ripleymj** [comment]
Seems good for now. If we find more needs, for fall, we can consider a step in common to find the UID of the wrapper or cinnamon-session, or pass a preferred UID from the wrapper as an extra variable in the ansible-pull run.

**Pull request merged**
