### PR TITLE
Add process for adding a new class to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Advill**
draft fix for #258

### CODE REVIEW

**Comment by ripleymj** [comment]
Depending on how #261 goes, we might need to untangle the git history of this branch before merging.

**Comment by Advill** [comment]
Oh yeah you're right, thought I was safe using branches, turns out I was mistaken.

**Comment by kylelaker** [comment]
If you want to, you should be able to `git rebase -i master` and then just not pick the 430-related commits. Alternatively, we can just clean this up after #261 gets merged.

**Comment by ripleymj** [comment]
Branches are still safe, but it looks like you got a branch of a branch, rather than a 2nd branch off master. Do the thing Kyle said, then force push it back here.

**Comment by Advill** [comment]
Ok, This should be untangled from the programming-languages update, check me to be sure though.

**Pull request merged**
